In [49]:
import pandas as pd
df=pd.read_csv("/Users/anishjain/Downloads/train_u6lujuX_CVtuZ9i (1).csv")

In [50]:
print(df.head())
print(df.tail())
print(df.shape)

    Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No
1  LP001003   Male     Yes          1      Graduate            No
2  LP001005   Male     Yes          0      Graduate           Yes
3  LP001006   Male     Yes          0  Not Graduate            No
4  LP001008   Male      No          0      Graduate            No

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0
1             4583             1508.0       128.0             360.0
2             3000                0.0        66.0             360.0
3             2583             2358.0       120.0             360.0
4             6000                0.0       141.0             360.0

   Credit_History Property_Area Loan_Status
0             1.0         Urban           Y
1             1.0         Rural           N
2             1.0         Urban           Y
3             1.0         Urban           Y
4             1.0         Urban           Y
      Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No
610  LP002979    Male     Yes         3+  Graduate            No
611  LP002983    Male     Yes          1  Graduate            No
612  LP002984    Male     Yes          2  Graduate            No
613  LP002990  Female      No          0  Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N
(614, 13)

In [51]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [53]:
df=df.dropna()

In [54]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [55]:
df.shape

(480, 13)

In [56]:
df['Married'].unique()

array(['Yes', 'No'], dtype=object)

In [57]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

In [59]:
df['Married'] = df['Married'].map({'Yes': 1, 'No': 0})

In [61]:
df['Education'] = df['Education'].map({'Graduate': 1, 'Not Graduate': 0})

In [63]:
df['Self_Employed'] = df['Self_Employed'].map({'Yes': 1, 'No': 0})

In [65]:
df['Loan_ID'] = df['Loan_ID'].str.extract(r'(\d+)')

In [66]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,001003,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,Rural,N
2,001005,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,Urban,Y
3,001006,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,001008,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,Urban,Y
5,001011,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,Urban,Y

In [67]:

df['Property_Area'] = df['Property_Area'].map({'Rural': 0, 'Urban': 1,'Semiurban': 2})

In [69]:
df['Loan_Status'] = df['Loan_Status'].map({'Y': 1, 'N': 0})

In [71]:
df['Dependents'] = df['Dependents'].replace('3+', '3')

In [76]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,001003,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0
2,001005,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,1
3,001006,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,1
4,001008,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,1
5,001011,1,1,2,1,1,5417,4196.0,267.0,360.0,1.0,1,1

In [77]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# Define features and target
features = df[['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
               'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
               'Loan_Amount_Term', 'Credit_History', 'Property_Area']]
Y = df['Loan_Status']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=42)

# Train a classification model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.46      0.59        28
           1       0.81      0.96      0.88        68

    accuracy                           0.81        96
   macro avg       0.81      0.71      0.73        96
weighted avg       0.81      0.81      0.79        96

Accuracy: 0.8125

In [78]:
y_pred

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1])

In [80]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report

# Split the dataset
#X_train, X_test, y_train, y_test = train_test_split(, y, test_size=0.2, random_state=42)

# Train an SVM classifier
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# Evaluate
y_pred1= model.predict(X_test)
print(classification_report(y_test, y_pred))
print(y_pred1)
print("Accuracy:", accuracy_score(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.81      0.46      0.59        28
           1       0.81      0.96      0.88        68

    accuracy                           0.81        96
   macro avg       0.81      0.71      0.73        96
weighted avg       0.81      0.81      0.79        96

[1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1]
Accuracy: 0.7604166666666666

In [86]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model
logreg_model = LogisticRegression(max_iter=5000, solver='lbfgs', C=10)
logreg_model.fit(X_train_scaled, y_train)
logreg_pred = logreg_model.predict(X_test_scaled)

# Evaluation
print("----- Logistic Regression Model -----")
print("Accuracy:", accuracy_score(y_test, logreg_pred))
print("Classification Report:\n", classification_report(y_test, logreg_pred))

----- Logistic Regression Model -----
Accuracy: 0.8229166666666666
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.39      0.56        28
           1       0.80      1.00      0.89        68

    accuracy                           0.82        96
   macro avg       0.90      0.70      0.73        96
weighted avg       0.86      0.82      0.79        96